Repository ikuseiGmbH/smart-village-app-humhub-ext, pull requests merged in 2022-08, with the labels that each got.

#51 Updated text from Beiträge to Stream
  messages/de/SpaceModule.base.php
Labels: wording

#50 All registered users should be able to get membership list of the space #45
  Events.php
  controllers/space/MembershipController.php
  docs/postman/Smart Village API.postman_collection.json
Labels: api, space

#52 Wording gruppen und vereine
  messages/de/AdminModule.base.php
  messages/de/AdminModule.user.php
  messages/de/DirectoryModule.base.php
Labels: wording

#56 Allow access of user by id by registered users #48
  Events.php
  controllers/user/UserFindController.php
  docs/postman/Smart Village API.postman_collection.json
Labels: api

#53 fix: updated text for Space into Gruppen und Vereine
  messages/de/ActiviyModule.base.php
  messages/de/AdminModule.base.php
  messages/de/AdminModule.module.php
  messages/de/AdminModule.user.php
  messages/de/DirectoryModule.base.php
  messages/de/SearchModule.base.php
  messages/de/SpaceModule.base.php
  messages/de/UserModule.profile.php
Labels: wording
